### ISSUE TITLE
输入验证数量超过100就提示No available proxies found.

### ISSUE THREAD

**Issue by n1utra** [Seven1an/SocksHunter#1]
当输入验证数量超过100就直接提示No available proxies found.，这个是为什么
![image](https://github.com/user-attachments/assets/52474de7-0302-4f68-829a-d887602f3019)
![image](https://github.com/user-attachments/assets/6671d73a-2919-4ff1-b435-364bbd26b55e)

**Comment by Seven1an** [comment]
感谢提交，近期准备更新再优化一下

**Comment by n1utra** [comment]
师傅你好，我看了下代码，验证数量会做为size参数传入请求中，但是对fofa发送请求时超过100就会返回错误
![image](https://github.com/user-attachments/assets/dd08c2c1-1385-4da2-a966-5e99363dd48f)
![image](https://github.com/user-attachments/assets/5da8fea6-e5a3-48f5-ab02-f02f0ddeef76)
不过fofa写的最大支持10000，不知道为什么会出现问题
![image](https://github.com/user-attachments/assets/dfee8c0a-3b19-4388-a725-be7793d86b4f)

**Comment by Seven1an** [comment]
谢谢你

**Comment by Seven1an** [comment]
可以留个联系方式么

**Comment by n1utra** [comment]
我加你哇，扫博客上面的二维码可以吗

**Comment by Seven1an** [comment]
ok
